// utils/iconMapping.ts
import {
  Shield,
  Users,
  BookOpen,
  FileText,
  Folder,
  BarChart3,
  Settings,
  Home,
  GraduationCap,
  Calendar,
  MessageSquare,
  Landmark,
  Sliders,
  Globe,
  Wrench,
  UserCircle,
  Layout,
  Database,
  Bell,
  HelpCircle,
  MoreVertical,
  PlusCircle,
  Edit,
  Trash,
  Eye,
  Download,
  Upload,
  Search,
  Filter,
  ChevronRight,
  ChevronDown,
  Check,
  X,
  Save,
  Loader2,
  ShieldCheck,
  FolderOpen,
  BarChart,
  File,
  Book,
  Target,
  Award,
  CreditCard,
  DollarSign,
  Receipt,
  Building,
  School,
  Briefcase,
  Mail,
  Phone,
  MapPin,
  Globe as GlobeIcon,
  Lock,
  Unlock,
  Key,
  UserPlus,
  UserMinus,
  UserCheck,
  Users as UsersIcon,
  Bookmark,
  Star,
  Heart,
  Share,
  Copy,
  Link,
  ExternalLink,
  Maximize,
  Minimize,
  RefreshCw,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Grid,
  List,
  Menu,
  Sidebar,
  LayoutDashboard,
  PieChart,
  LineChart,
  TrendingUp,
  TrendingDown,
  Activity,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Clock,
  CalendarDays,
  Watch,
  Timer,
  BellRing,
  Music,
  Video,
  Image,
  Camera,
  Mic,
  Headphones,
  Volume2,
  VolumeX,
  Play,
  Pause,
  StopCircle,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
} from "lucide-react";

export const iconMap: Record<string, any> = {
  // Default and common icons
  Shield,
  Users,
  BookOpen,
  FileText,
  Folder,
  BarChart3,
  Settings,
  Home,
  GraduationCap,
  Calendar,
  MessageSquare,
  Landmark,
  Sliders,
  Globe,
  Wrench,
  UserCircle,
  Layout,
  Database,
  Bell,
  HelpCircle,
  MoreVertical,
  
  // Dashboard and layout
  LayoutDashboard,
  Sidebar,
  Menu,
  Grid,
  List,
  
  // Files and content
  File,
  FolderOpen,
  Upload,
  Download,
  Copy,
  Link,
  ExternalLink,
  
  // Books and learning
  Book,
  Bookmark,
  Award,
  Target,
  
  // Users and people
  UserPlus,
  UserMinus,
  UserCheck,
  UsersIcon,
  
  // Finance
  CreditCard,
  DollarSign,
  Receipt,
  
  // Business
  Building,
  School,
  Briefcase,
  
  // Communication
  Mail,
  Phone,
  MapPin,
  GlobeIcon,
  
  // Security
  Lock,
  Unlock,
  Key,
  
  // Actions
  Edit,
  Trash,
  Eye,
  Search,
  Filter,
  PlusCircle,
  Save,
  Check,
  X,
  
  // Navigation
  ChevronRight,
  ChevronDown,
  
  // Status
  CheckCircle,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  ThumbsUp,
  ThumbsDown,
  
  // Time
  Clock,
  CalendarDays,
  Watch,
  Timer,
  
  // Media
  Music,
  Video,
  Image,
  Camera,
  Mic,
  Headphones,
  Volume2,
  VolumeX,
  Play,
  Pause,
  StopCircle,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  
  // Charts and analytics
  BarChart,
  PieChart,
  LineChart,
  TrendingUp,
  TrendingDown,
  Activity,
  
  // Emotions
  Smile,
  Frown,
  Meh,
  
  // Loading
  Loader2,
  RefreshCw,
  RotateCcw,
  
  // Others
  BellRing,
  ShieldCheck,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  Star,
  Heart,
  Share,
};

export const getIconComponent = (iconName: string) => {
  return iconMap[iconName] || Shield; // Default to Shield if icon not found
};

// Available colors for permissions
export const availableColors = [
  "blue",
  "green",
  "purple",
  "orange",
  "teal",
  "gray",
  "red",
  "pink",
  "indigo",
  "yellow",
  "cyan",
  "emerald",
  "violet",
  "fuchsia",
  "rose",
  "amber",
  "lime",
  "sky",
  "stone"
];

// Color classes mapping
export const colorClasses: Record<string, any> = {
  blue: {
    bg: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-600",
    bgLight: "bg-blue-100",
    textLight: "text-blue-700",
    hover: "hover:bg-blue-50",
  },
  green: {
    bg: "bg-green-50",
    border: "border-green-200",
    text: "text-green-600",
    bgLight: "bg-green-100",
    textLight: "text-green-700",
    hover: "hover:bg-green-50",
  },
  purple: {
    bg: "bg-purple-50",
    border: "border-purple-200",
    text: "text-purple-600",
    bgLight: "bg-purple-100",
    textLight: "text-purple-700",
    hover: "hover:bg-purple-50",
  },
  orange: {
    bg: "bg-orange-50",
    border: "border-orange-200",
    text: "text-orange-600",
    bgLight: "bg-orange-100",
    textLight: "text-orange-700",
    hover: "hover:bg-orange-50",
  },
  teal: {
    bg: "bg-teal-50",
    border: "border-teal-200",
    text: "text-teal-600",
    bgLight: "bg-teal-100",
    textLight: "text-teal-700",
    hover: "hover:bg-teal-50",
  },
  gray: {
    bg: "bg-gray-50",
    border: "border-gray-200",
    text: "text-gray-600",
    bgLight: "bg-gray-100",
    textLight: "text-gray-700",
    hover: "hover:bg-gray-50",
  },
  red: {
    bg: "bg-red-50",
    border: "border-red-200",
    text: "text-red-600",
    bgLight: "bg-red-100",
    textLight: "text-red-700",
    hover: "hover:bg-red-50",
  },
  pink: {
    bg: "bg-pink-50",
    border: "border-pink-200",
    text: "text-pink-600",
    bgLight: "bg-pink-100",
    textLight: "text-pink-700",
    hover: "hover:bg-pink-50",
  },
  indigo: {
    bg: "bg-indigo-50",
    border: "border-indigo-200",
    text: "text-indigo-600",
    bgLight: "bg-indigo-100",
    textLight: "text-indigo-700",
    hover: "hover:bg-indigo-50",
  },
  yellow: {
    bg: "bg-yellow-50",
    border: "border-yellow-200",
    text: "text-yellow-600",
    bgLight: "bg-yellow-100",
    textLight: "text-yellow-700",
    hover: "hover:bg-yellow-50",
  },
  cyan: {
    bg: "bg-cyan-50",
    border: "border-cyan-200",
    text: "text-cyan-600",
    bgLight: "bg-cyan-100",
    textLight: "text-cyan-700",
    hover: "hover:bg-cyan-50",
  },
};