"use client"

// Structure template: "5 modules, each with 3 topics of 2 sub topics" drawn as
// a blank grid, with an Add button in every empty slot.
//
// Nothing here is saved to the server. The hierarchy APIs refuse an item
// without a title, and a blank named "Module 1" would leak into every report
// and calendar that reads the course. So the template is a LAYOUT HINT, kept per
// course + phase in localStorage: counts per module, applied over whatever
// actually exists. Slot k of module i is empty exactly while module i has
// fewer than k real children, so each Add fills one slot and the grid
// shrinks as the course gets written, with no bookkeeping to keep in sync.
//
// Template module i pairs with the i-th real module in display order.
// Slots never displace real rows: real children render first, then the
// empty slots after them.

import { useCallback, useEffect, useState } from "react"

export type TemplateModule = {
    /** Sub modules per module (courses with a Sub Module level). */
    subModules: number
    /** Topics per sub module, or per module when there is no Sub Module level. */
    topics: number
    /** Sub topics per topic. */
    subTopics: number
}
export type PedagogyTemplate = { modules: TemplateModule[] }

export type TemplateLevel = "module" | "submodule" | "topic" | "subtopic"

const ID_KEY: Record<TemplateLevel, string> = { module: "moduleId", submodule: "subModuleId", topic: "topicId", subtopic: "subtopicId" }
const NAME_KEY: Record<TemplateLevel, string> = { module: "moduleName", submodule: "subModuleName", topic: "topicName", subtopic: "subtopicName" }

type Node = {
    level: TemplateLevel
    id: string
    name: string
    /** An empty slot: generated by the template, or the table's own placeholder. */
    empty: boolean
    children: Node[]
    srcIndex?: number
}

export type TemplateSlotItem = {
    kind: "slot"
    key: string
    /** Row-shaped ids for this slot, real ancestors included. */
    ids: Record<TemplateLevel, string | null>
    /** Which level cells start on this row, and their rowSpans. */
    starts: Partial<Record<TemplateLevel, number>>
    /** Per level: does the item at that level exist on the server yet? */
    real: Record<TemplateLevel, boolean>
}
export type TemplateRealItem = { kind: "real"; row: any; srcIndex: number }
export type TemplateLayout = {
    items: (TemplateRealItem | TemplateSlotItem)[]
    /** rowSpans by id per level, covering real AND slot rows. */
    spans: { module: Record<string, number>; submodule: Record<string, number>; topic: Record<string, number> }
    /** Empty slots still to fill (template slots + placeholders they pad). */
    remaining: number
}

export function hierarchyLevelsOf(course: any): TemplateLevel[] {
    const h: string[] = course?.courseHierarchy || []
    return ([
        h.includes("Module") && "module",
        h.includes("Sub Module") && "submodule",
        h.includes("Topic") && "topic",
        h.includes("Sub Topic") && "subtopic",
    ].filter(Boolean)) as TemplateLevel[]
}

const isEmptyName = (id: any, name: any) =>
    !id || String(id).includes("placeholder") || name === "-" || name === "" || String(name ?? "").includes("Default")

export function buildTemplateLayout(tableRows: any[], template: PedagogyTemplate, levels: TemplateLevel[]): TemplateLayout | null {
    if (!levels.length || levels[0] !== "module") return null

    // ── Tree of what exists, built from the table's own rows (so ordering and
    //    placeholder rows are exactly what the table shows). ──
    const roots: Node[] = []
    tableRows.forEach((row, srcIndex) => {
        let siblings = roots
        levels.forEach((level, depth) => {
            const id = String(row[ID_KEY[level]] ?? `${level}-${srcIndex}`)
            let node = siblings.find(n => n.id === id)
            if (!node || depth === levels.length - 1) {
                node = { level, id, name: row[NAME_KEY[level]] ?? "", empty: isEmptyName(row[ID_KEY[level]], row[NAME_KEY[level]]), children: [] }
                if (depth === levels.length - 1) node.srcIndex = srcIndex
                siblings.push(node)
            }
            siblings = node.children
        })
    })

    // ── Pad with empty slots up to the template's counts ──
    let seq = 0
    const expected = (level: TemplateLevel, tm: TemplateModule) =>
        level === "submodule" ? tm.subModules : level === "topic" ? tm.topics : level === "subtopic" ? tm.subTopics : 0
    const generate = (depth: number, tm: TemplateModule): Node => {
        const level = levels[depth]
        const node: Node = { level, id: `tpl-placeholder-${level}-${seq++}`, name: "-", empty: true, children: [] }
        if (depth < levels.length - 1) {
            const n = Math.max(1, expected(levels[depth + 1], tm))
            for (let i = 0; i < n; i++) node.children.push(generate(depth + 1, tm))
        }
        return node
    }
    const pad = (node: Node, depth: number, tm: TemplateModule) => {
        if (depth >= levels.length - 1) return
        const want = expected(levels[depth + 1], tm)
        for (const child of node.children) pad(child, depth + 1, tm)
        for (let i = node.children.length; i < want; i++) node.children.push(generate(depth + 1, tm))
    }
    template.modules.forEach((tm, i) => {
        if (i < roots.length) pad(roots[i], 0, tm)
        else roots.push(generate(0, tm))
    })

    // ── Flatten, recording spans and which cells start on each row ──
    const spans = { module: {} as Record<string, number>, submodule: {} as Record<string, number>, topic: {} as Record<string, number> }
    const leafCount = (n: Node): number => (n.children.length ? n.children.reduce((s, c) => s + leafCount(c), 0) : 1)
    const items: TemplateLayout["items"] = []
    let remaining = 0
    const walk = (node: Node, path: Node[]) => {
        const here = [...path, node]
        if (node.level !== "subtopic") spans[node.level as "module" | "submodule" | "topic"][node.id] = leafCount(node)
        if (node.children.length) { node.children.forEach(c => walk(c, here)); return }
        if (node.srcIndex !== undefined) {
            items.push({ kind: "real", row: tableRows[node.srcIndex], srcIndex: node.srcIndex })
            return
        }
        const ids = { module: null, submodule: null, topic: null, subtopic: null } as TemplateSlotItem["ids"]
        const real = { module: false, submodule: false, topic: false, subtopic: false } as TemplateSlotItem["real"]
        const starts: TemplateSlotItem["starts"] = {}
        here.forEach((n) => {
            ids[n.level] = n.id
            real[n.level] = !n.empty
            // A cell starts on this row when this row is the node's first leaf.
            let first: Node = n
            while (first.children.length) first = first.children[0]
            if (first === node) {
                starts[n.level] = leafCount(n)
                if (n.empty) remaining++
            }
        })
        items.push({ kind: "slot", key: node.id, ids, starts, real })
    }
    roots.forEach(r => walk(r, []))
    return { items, spans, remaining }
}

// ── Persistence ──────────────────────────────────────────────────────────────

const storageKey = (courseId?: string, phase?: string) => `pedagogy-template:${courseId || ""}:${phase || ""}`

export function usePedagogyTemplate(courseId?: string, phase?: string) {
    const [template, setTemplateState] = useState<PedagogyTemplate | null>(null)
    useEffect(() => {
        if (!courseId) { setTemplateState(null); return }
        try {
            const raw = localStorage.getItem(storageKey(courseId, phase))
            setTemplateState(raw ? JSON.parse(raw) : null)
        } catch { setTemplateState(null) }
    }, [courseId, phase])

    const setTemplate = useCallback((next: PedagogyTemplate | null) => {
        setTemplateState(next)
        try {
            if (next) localStorage.setItem(storageKey(courseId, phase), JSON.stringify(next))
            else localStorage.removeItem(storageKey(courseId, phase))
        } catch { /* private mode: the template simply won't survive a reload */ }
    }, [courseId, phase])

    return { template, setTemplate }
}
